export const config = { runtime: "edge" };

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
};

export default async function handler(request) {
  if (request.method === "OPTIONS") return new Response(null, { headers: CORS });
  if (request.method !== "POST") return new Response("Method not allowed", { status: 405 });

  try {
    const { accessToken, trackUris, playlistName, moodLabel } = await request.json();
    if (!accessToken || !trackUris?.length) {
      return new Response(JSON.stringify({ error: "Missing token or tracks" }), {
        status: 400, headers: { ...CORS, "Content-Type": "application/json" },
      });
    }

    // Get user profile
    const profileRes = await fetch("https://api.spotify.com/v1/me", {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    const profile = await profileRes.json();
    const userId = profile.id;

    // Create playlist
    const createRes = await fetch(`https://api.spotify.com/v1/users/${userId}/playlists`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: `Moodwave: ${moodLabel}`,
        description: `Generated by Moodwave for the mood: ${playlistName}. buildbyace.vercel.app`,
        public: false,
      }),
    });
    const playlist = await createRes.json();

    // Add tracks
    await fetch(`https://api.spotify.com/v1/playlists/${playlist.id}/tracks`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ uris: trackUris }),
    });

    return new Response(
      JSON.stringify({ playlistUrl: playlist.external_urls?.spotify, playlistId: playlist.id }),
      { headers: { ...CORS, "Content-Type": "application/json" } }
    );

  } catch (e) {
    return new Response(JSON.stringify({ error: e.message }), {
      status: 500, headers: { ...CORS, "Content-Type": "application/json" },
    });
  }
}
